name: "Hello"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./lib
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: "needs-review"
